# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
